import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import {
  Box,
  Heading,
  Container,
  Text,
  Button,
  Stack,
  Icon,
  useColorModeValue,
  createIcon,
  Input,
  InputGroup,
  InputRightElement,
  IconButton,
  Badge,
} from '@chakra-ui/react';
import { SearchIcon } from '@chakra-ui/icons';

export default function Home({ categories }) {
  const [hoveredCategory, setHoveredCategory] = useState(null);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Container maxW={'3xl'}>
        <Stack
          as={Box}
          textAlign={'center'}
          spacing={{ base: 8, md: 14 }}
          py={{ base: 20, md: 36 }}
        >
          <Heading
            fontWeight={600}
            fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}
            lineHeight={'110%'}
          >
            Find Best AI tools to<br />
            <Text as={'span'} color={'green.400'}>
              simplify your task
            </Text>
          </Heading>

          <Stack
            direction={'column'}
            spacing={3}
            align={'center'}
            alignSelf={'center'}
            position={'relative'}
          >
            <InputGroup minW={['250px', '250px', '350px']}>
              <Input placeholder="Search" />
              <InputRightElement>
                <IconButton
                  aria-label="Search"
                  icon={<SearchIcon />}
                  bg="lightblue"
                />
              </InputRightElement>
            </InputGroup>

          
          </Stack>

          <Stack  maxW={'3xl'} direction="row" spacing={2}>
            <Box>
              {categories?.map((category) => (
                <Badge
                  key={category.id}
                  variant="outline"
                  colorScheme={hoveredCategory === category.id ? 'green' : 'gray'}
                  onMouseEnter={() => setHoveredCategory(category.id)}
                  onMouseLeave={() => setHoveredCategory(null)}
                  _hover={{
                    cursor: 'pointer',
                    colorScheme: 'green',
                    transform: 'translateX(2px)',
                  }}
                >
                  {category.name}
                </Badge>
              ))}
            </Box>
            </Stack>
        </Stack>
      </Container>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch('http://api.aitoolsnext.com/getCategories');
  const categories = await response.json();

  return {
    props: {
      categories,
    },
  };
}
